[package]
name = "rust_hello"
version = "0.1.0"
authors = ["Daan de Graaf <daan.de.graaf@prodrive-technologies.com>"]
edition = "2018"

[dependencies]
nix = "0.13"
libc = "0.2"
failure = "0.1"
actix-web = "0.7"
